spring:
  application:
    name: be-interview-prep
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      lifecycle-management: start-only
