CREATE TABLE book (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    author         VARCHAR(255) NOT NULL,
    isbn           VARCHAR(17)  NOT NULL,
    published_year INTEGER      NOT NULL,
    borrowed       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_book_isbn UNIQUE (isbn)
);

CREATE TABLE loan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT    NOT NULL,
    member_id   BIGINT    NOT NULL,
    borrowed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    returned_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_loan_book FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);

CREATE INDEX idx_loan_book_id ON loan (book_id);
