CREATE TABLE expense (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount       NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    category     VARCHAR(20)    NOT NULL,
    expense_date DATE           NOT NULL,
    note         VARCHAR(500)
);

CREATE INDEX idx_expense_date_category ON expense (expense_date, category);
