CREATE TABLE doctor (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    specialty  VARCHAR(100) NOT NULL,
    work_start TIME         NOT NULL,
    work_end   TIME         NOT NULL,
    CONSTRAINT ck_doctor_working_hours CHECK (work_start < work_end)
);

CREATE TABLE booking (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id       BIGINT      NOT NULL REFERENCES doctor (id),
    patient_id      BIGINT      NOT NULL,
    start_time      TIMESTAMP   NOT NULL,
    end_time        TIMESTAMP   NOT NULL,
    status          VARCHAR(20) NOT NULL,
    hold_expires_at TIMESTAMPTZ NOT NULL,
    confirmed_at    TIMESTAMPTZ,
    cancelled_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT ck_booking_status CHECK (status IN ('HELD', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_booking_time_range CHECK (start_time < end_time)
);

CREATE UNIQUE INDEX uq_booking_active_slot
    ON booking (doctor_id, start_time)
    WHERE status IN ('HELD', 'CONFIRMED');

CREATE INDEX ix_booking_held_expiry
    ON booking (hold_expires_at)
    WHERE status = 'HELD';

INSERT INTO doctor (name, specialty, work_start, work_end) VALUES
    ('Dr. Asha Menon', 'General Practice', '09:00', '17:00'),
    ('Dr. Rahul Nair', 'Cardiology', '10:00', '14:00'),
    ('Dr. Sara Thomas', 'Dermatology', '13:00', '18:00');
